import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/Header';
import Main from '../components/Main';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isDark />
      <div className={styles.homepage}>
        <div>
          <Main />
        </div>
      </div>
    </div>
  );
};

export default Home;
